"""empty message

Revision ID: 673faf78487f
Revises: f16dfdef63ac
Create Date: 2020-11-25 21:40:02.480429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673faf78487f'
down_revision = 'f16dfdef63ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('submitter_id', sa.String(length=40), nullable=True))
    op.drop_column('ticket', 't_submitter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('t_submitter', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('ticket', 'submitter_id')
    # ### end Alembic commands ###
