"""empty message

Revision ID: 687ebb0abe44
Revises: 673faf78487f
Create Date: 2020-11-28 23:35:14.808102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687ebb0abe44'
down_revision = '673faf78487f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('submitter_email', sa.String(), nullable=True))
    op.drop_column('ticket', 'submitter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('submitter_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('ticket', 'submitter_email')
    # ### end Alembic commands ###
