"""empty message

Revision ID: 7e9520f86a2d
Revises: 687ebb0abe44
Create Date: 2020-12-03 00:25:51.329040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9520f86a2d'
down_revision = '687ebb0abe44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=40), nullable=True),
    sa.Column('emp_email', sa.String(length=40), nullable=True),
    sa.Column('emp_pwd', sa.String(length=100), nullable=True),
    sa.Column('emp_role', sa.String(length=20), nullable=True),
    sa.Column('update_date', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('emp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
