"""empty message

Revision ID: 905e3242e3d5
Revises: 
Create Date: 2020-12-05 20:54:37.689260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905e3242e3d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('t_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_table('map_user_proj',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('user_assign_date', sa.String(length=20), nullable=True),
    sa.Column('user_end_date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('map_id')
    )
    op.create_table('project',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('p_name', sa.String(length=40), nullable=True),
    sa.Column('p_desc', sa.String(length=100), nullable=True),
    sa.Column('p_start_date', sa.String(length=20), nullable=True),
    sa.Column('p_end_date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('ticket',
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('t_title', sa.String(length=40), nullable=True),
    sa.Column('t_desc', sa.String(length=100), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('submitter_email', sa.String(), nullable=True),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('t_priority', sa.String(length=40), nullable=True),
    sa.Column('t_status', sa.String(length=40), nullable=True),
    sa.Column('t_type', sa.String(length=40), nullable=True),
    sa.Column('t_create_date', sa.String(length=40), nullable=True),
    sa.Column('t_close_date', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('t_id')
    )
    op.create_table('ticket_history',
    sa.Column('t_history_id', sa.Integer(), nullable=False),
    sa.Column('t_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('t_status', sa.String(length=10), nullable=True),
    sa.Column('t_update_date', sa.String(length=20), nullable=True),
    sa.Column('t_priority', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('t_history_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=40), nullable=True),
    sa.Column('user_email', sa.String(length=40), nullable=True),
    sa.Column('user_pwd', sa.String(length=100), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('update_date', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ticket_history')
    op.drop_table('ticket')
    op.drop_table('project')
    op.drop_table('map_user_proj')
    op.drop_table('comment')
    # ### end Alembic commands ###
