"""empty message

Revision ID: 95f60adea272
Revises: 7e9520f86a2d
Create Date: 2020-12-03 00:51:13.571996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f60adea272'
down_revision = '7e9520f86a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_emp_proj',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('emp_role', sa.String(length=20), nullable=True),
    sa.Column('emp_assign_date', sa.String(length=20), nullable=True),
    sa.Column('emp_end_date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('map_id')
    )
    op.create_table('project',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('p_name', sa.String(length=40), nullable=True),
    sa.Column('p_desc', sa.String(length=100), nullable=True),
    sa.Column('p_start_date', sa.String(length=20), nullable=True),
    sa.Column('p_end_date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('p_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('map_emp_proj')
    # ### end Alembic commands ###
